/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionestudiantes.vista;

import com.mycompany.gestionestudiantes.controlador.EstudianteControlador;
import com.mycompany.gestionestudiantes.modelo.Estudiante;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class VistaEstudiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstudiante.class.getName());
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    /**
     * Creates new form VistaEstudiante
     */
    public VistaEstudiante() {
        initComponents();
        
        probarConexion();
        configurarTabla();
        validarDatos();
        
        
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ID = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        ID.setText("Id:");
        ID.setName(""); // NOI18N

        Nombre.setText("Nombre :");

        Apellido.setText("Apellido:");

        Email.setText("Email:");

        Edad.setText("Edad:");

        Carrera.setText("Carrera:");

        txtId.setText("1001");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.setText("Alex");

        txtApellido.setText("Garcia");

        txtEmail.setText("alex@gmail.com");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtEdad.setText("17");

        txtCarrera.setText("software");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstudiantes.setName(""); // NOI18N
        jScrollPane2.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtApellido)
                                    .addComponent(txtNombre)
                                    .addComponent(txtId)
                                    .addComponent(txtEdad)
                                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carrera))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // En el constructor de VistaEstudiante, después de initComponents():
private void configurarTabla() {
    tblEstudiantes.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && tblEstudiantes.getSelectedRow() >= 0) {
            int fila = tblEstudiantes.getSelectedRow();
            
            txtId.setText(tblEstudiantes.getValueAt(fila, 0).toString());
            txtNombre.setText(tblEstudiantes.getValueAt(fila, 1).toString());
            txtApellido.setText(tblEstudiantes.getValueAt(fila, 2).toString());
            txtEmail.setText(tblEstudiantes.getValueAt(fila, 3).toString());
            txtEdad.setText(tblEstudiantes.getValueAt(fila, 4).toString());
            txtCarrera.setText(tblEstudiantes.getValueAt(fila, 5).toString());
        }
    });
}



private boolean validarDatos() {
    // Validar que ID sea número
    try {
        Integer.parseInt(txtId.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID debe ser número", "Error", JOptionPane.ERROR_MESSAGE);
        txtId.requestFocus();
        return false;
    }
    
    // Validar que nombre no esté vacío
    if (txtNombre.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        txtNombre.requestFocus();
        return false;
    }
    
    return true;
}
    
    
    
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    
    
    
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

    try {
        // 1. Obtener datos de los campos
        int id = Integer.parseInt(txtId.getText().trim());
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String email = txtEmail.getText().trim();
        int edad = Integer.parseInt(txtEdad.getText().trim());
        String carrera = txtCarrera.getText().trim();
        
        // 2. Crear objeto Estudiante
        Estudiante e = new Estudiante(id, nombre, apellido, email, edad, carrera);
        
        // 3. Llamar al controlador
        EstudianteControlador controlador = new EstudianteControlador();
        boolean resultado = controlador.crear(e); // ← ahora retorna boolean
        
        // 4. Mostrar resultado
        if (resultado) {
            JOptionPane.showMessageDialog(this, 
                """
                Estudiante creado exitosamente
                ID: """ + id + "\n" +
                "Nombre: " + nombre + " " + apellido,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            // 5. Actualizar tabla
            cargarDatos();
            
            // 6. Limpiar campos (opcional)
            // limpiarCampos();
            
        } else {
            JOptionPane.showMessageDialog(this, """
                                                No se pudo crear el estudiante
                                                Posible causa: ID duplicado""",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            """
            Error: ID y Edad deben ser numeros
            ID: """ + txtId.getText() + "\n" +
            "Edad: " + txtEdad.getText(),
            "Error de formato",
            JOptionPane.ERROR_MESSAGE);
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btnCrearActionPerformed

    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        Estudiante e = new Estudiante(
        Integer.parseInt(txtId.getText()),
        txtNombre.getText(),
        txtApellido.getText(),
        txtEmail.getText(),
        Integer.parseInt(txtEdad.getText()),
        txtCarrera.getText()
    );

    new EstudianteControlador().actualizar(e);
    
    }//GEN-LAST:event_btnActualizarActionPerformed

    
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                                              
    try {
        int id = Integer.parseInt(txtId.getText().trim());
        
        // Confirmar antes de eliminar
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de eliminar al estudiante con ID: " + id + "?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            EstudianteControlador controlador = new EstudianteControlador();
            boolean resultado = controlador.eliminar(id);
            
            if (resultado) {
                JOptionPane.showMessageDialog(this, 
                    "Estudiante eliminado exitosamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // ¡IMPORTANTE! Limpiar campos Y actualizar tabla
                limpiarCampos();
                cargarDatos();  // ← ESTA LÍNEA ES CLAVE
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al eliminar. Verifique que el ID exista", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Error: El ID debe ser un número válido", 
            "Error de formato", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtEdad.setText("");
        txtCarrera.setText("");
        txtId.requestFocus(); // Poner cursor en ID
}
    
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaEstudiante().setVisible(true));
    }
    
    
    
public final void cargarDatos() {
    EstudianteControlador controlador = new EstudianteControlador();
    List<Estudiante> listaEstudiantes = controlador.listar();
    
    String[] columnas = {
        "ID", "Nombre", "Apellido", "Email", "Edad", "Carrera"
    };
    
    modeloTabla = new DefaultTableModel(columnas, 0);
    tblEstudiantes.setModel(modeloTabla);
    
    for (Estudiante e : listaEstudiantes) {
        modeloTabla.addRow(new Object[] {
            e.getId(),
            e.getNombre(),
            e.getApellido(),
            e.getEmail(),
            e.getEdad(),
            e.getCarrera()
        });
    }
}



private void probarConexion() {
    try {
        System.out.println("Probando conexión desde VistaEstudiante...");
        boolean conexionExitosa = com.mycompany.gestionestudiantes.basedatos.ConexionMongoDB.probarConexion();
        
        if (conexionExitosa) {
            JOptionPane.showMessageDialog(this, """
                                                Conexión a MongoDB establecida correctamente
                                                Base de datos: Trabajo
                                                URI: mongodb://localhost:27017""",
                "Conexion Exitosa",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, """
                                                No se pudo conectar a MongoDB
                                                
                                                Verifica que:
                                                1. MongoDB este ejecutandose
                                                2. El puerto 27017 este disponible
                                                3. No haya firewall bloqueando""",
                "Error de Conexión",
                JOptionPane.ERROR_MESSAGE);
        }
    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Excepción",
            JOptionPane.ERROR_MESSAGE);
    }
}















    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
